# Generated by Django 6.0.1 on 2026-03-04 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favoritetrack',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoritetrack',
            name='track',
        ),
        migrations.RemoveField(
            model_name='favoritetrack',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='is_original',
        ),
        migrations.RemoveField(
            model_name='track',
            name='language',
        ),
        migrations.RemoveField(
            model_name='track',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='track',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/default_cover.jpg', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteplaylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='api.playlist'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='api.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trackgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_genres', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='trackgenre',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_genres', to='api.track'),
        ),
        migrations.AlterField(
            model_name='tracklike',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.track'),
        ),
        migrations.AlterField(
            model_name='tracklike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackstat',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trackstat', to='api.track'),
        ),
        migrations.AlterField(
            model_name='trendingtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_records', to='api.track'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='No bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['created_at'], name='api_track_created_2818ad_idx'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteTrack',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'track')},
        ),
    ]
