# Generated by Django 6.0.1 on 2026-03-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite_alter_favoritetrack_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(default='track_covers/default.png', upload_to='track_covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.FileField(default='tracks/default.mp3', upload_to='tracks/'),
        ),
    ]
